- name: Run Emby container
  hosts: Test
  tasks:
    - name: Start Emby container
      docker_container:
        name: Emby
        image: lscr.io/linuxserver/emby:latest
        state: started
        restart_policy: unless-stopped
        env:
          PUID: 1000
          PGID: 1000
          NVIDIA_DRIVER_CAPABILITIES: all
          NVIDIA_VISIBLE_DEVICES: all
          TZ: Europe/London
        ports:
          - "8096:8096"
          - "8920:8920"

- name: Run Radarr container
  hosts: Test
  tasks:
    - name: Start Radarr container
      docker_container:
        name: Radarr
        image: lscr.io/linuxserver/radarr
        state: started
        restart_policy: unless-stopped
        network_mode: container:Surfshark
        env:
          PUID: 1000
          PGID: 1000
          TZ: Europe/London

- name: container Portainer
  hosts: Test
  tasks:
    - name: Start Portainer container
      docker_container:
        name: Portainer
        image: portainer/portainer-ee:latest
        state: started
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        ports:
          - "9443:9443"
          - "8000:8000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /NVMe/Docker/Portainer:/data

