- name: Run Emby container
  hosts: Pig
  tasks:
    - name: Start Emby container
      docker_container:
        name: Emby
        image: lscr.io/linuxserver/emby:latest
        state: started
        restart_policy: unless-stopped
        env:
          PUID: 1000
          PGID: 1000
          NVIDIA_DRIVER_CAPABILITIES: all
          NVIDIA_VISIBLE_DEVICES: all
          TZ: Europe/London
        device_requests:
          - capabilities: [gpu]
        ports:
          - "8096:8096"
          - "8920:8920"
        volumes:
          - /NVMe/Docker/emby:/config
          - /NVMe/Emby:/NVMe
          - /Data/Media:/Media