- name: Run Radarr container
  hosts: Pig
  tasks:
    - name: Start Radarr container
      docker_container:
        name: Radarr
        image: lscr.io/linuxserver/radarr
        state: started
        restart_policy: unless-stopped
        network_mode: container:Surfshark
        env:
          PUID: 1000
          PGID: 1000
          TZ: Europe/London
        volumes:
          - /NVMe/Docker/Radarr:/config
          - /Data/Media/Movies:/movies
          - /Data/Downloads:/downloads