- name: Run Transmission container
  hosts: Pig
  tasks:
    - name: Run Transmission container
      docker_container:
        name: Transmission
        image: lscr.io/linuxserver/transmission
        state: started
        restart_policy: unless-stopped
        network_mode: container:gluetun-gluetun-1
        env:
          PUID: 1000
          PGID: 1000
          TZ: Europe/London
        volumes:
          - /NVMe/Docker/Transmission:/config
          - /Data/Downloads/incomplete:/downloads/incomplete
          - /Data/Downloads/complete:/downloads/complete
          - /Data/Watch:/watch