- name: Run Jackett container
  hosts: Test
  tasks:
    - name: Run Jackett container
      docker_container:
        name: Jackett
        image: lscr.io/linuxserver/jackett:latest
        state: started
        restart_policy: unless-stopped
        env:
          PUID: 1000
          PGID: 1000
          TZ: Europe/London
          AUTO_UPDATE: "true"
        ports:
          - "9117:9117"
        volumes:
          - /NVMe/Docker/jackett:/config