- name: Run Resilio Sync container
  hosts: Pig
  tasks:
    - name: Start Resilio Sync container
      docker_container:
        name: resilio-sync
        image: lscr.io/linuxserver/resilio-sync:latest
        state: started
        restart_policy: unless-stopped
        env:
          PUID: 1000
          PGID: 1000
          TZ: Etc/London
        ports:
          - "8888:8888"
          - "55555:55555"
        volumes:
          - /NVMe/Docker/Sync:/config
          - /Data:/Data