- hosts: Test
  become: true

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Emby container
      docker_container:
        name: Emby
        image: lscr.io/linuxserver/emby:latest
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          NVIDIA_DRIVER_CAPABILITIES: "all"
          NVIDIA_VISIBLE_DEVICES: "all"
          TZ: "Europe/London"
        ports:
          - "8096:8096"
          - "8920:8920"
        volumes:
          - /NVMe/Docker/emby:/config
          - /Data/Media:/Media
          - /NVMe:/NVMe/Emby
        runtime: "nvidia"

    - name: Radarr container
      docker_container:
        name: Radarr
        image: lscr.io/linuxserver/radarr
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - /NVMe/Docker/Radarr:/config
          - /Data/Media/Movies:/movies
          - /Data/Downloads:/downloads
        ports:
          - "7878:7878"

    - name: Sonarr container
      docker_container:
        name: Sonarr
        image: lscr.io/linuxserver/sonarr
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - /NVMe/Docker/Sonarr:/config
          - /Data/Media/TV:/tv
          - /Data/Downloads:/downloads
        ports:
          - "8989:8989"

    - name: Jackett container
      docker_container:
        name: Jackett
        image: lscr.io/linuxserver/jackett
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - /NVMe/Docker/Jackett:/config
        ports:
          - "9117:9117"

    - name: Ombi container
      docker_container:
        name: Ombi
        image: lscr.io/linuxserver/ombi
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - /NVMe/Docker/OMBI:/config
        ports:
          - "3579:3579"

    - name: Linarr container
      docker_container:
        name: Linarr
        image: lscr.io/linuxserver/linarr
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - /NVMe/Docker/Linarr:/config
          - /Data/Downloads:/downloads
          - /Data/Media/Music:/music
        ports:
          - "8686:8686"

    - name: Overseerr container
      docker_container:
        name: Overseerr
        image: lscr.io/linuxserver/overseerr
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - /NVMe/Docker/Overseerr:/config
        ports:
          - "5055:5055"

    - name: Prowarr container
      docker_container:
        name: Prowarr
        image: lscr.io/linuxserver/prowarr
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - /NVMe/Docker/prowarr:/config
        ports:
          - "9696:9696"

    - name: container Surfshark
      docker_container:
        name: Surfshark
        image: lqmcgaw/gluetun:latest
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
          VPN_SERVICE_PROVIDER: "surfshark"
          VPN_TYPE: "openvpn"
          WIREGUARD_PRIVATE_KEY: "SAduTTn+OWGokQ7ygwTLbUXdk3Or/OCscvhWEPCiwE8="
          WIREGUARD_ADDRESSES: "10.14.0.2/16"
          SERVER_COUNTRIES: "Netherlands"
        ports:
          - "9091:9091"
        capanilities:
          - NET_ADMIN

    - name: container Portainer
      docker_container:
        name: Portainer
        image: portainer/portainer-ee:latest
        state: started
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        ports:
          - "9443:9443"
          - "8000:8000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /NVMe/Docker/Portainer:/data

    - name: container Watchtower
      docker_container:
        name: Watchtower
        image: containrrr/watchtower
        state: started
        restart_policy: always
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: --cleanup

    - name: container Heimdall
      docker_container:
        name: Heimdall
        image: lscr.io/linuxserver/heimdall
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        ports:
          - "8080:8080"
        volumes:
          - /NVMe/Docker/Heimdall:/config
          
    - name: container Guacamole
      docker_container:
        name: Guacamole
        image: lscr.io/linuxserver/guacamole
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        ports:
          - "8081:8081"
        volumes:
          - /NVMe/Docker/Guacamole:/config

    - name: container Bookstack
      docker_container:
        name: Bookstack
        image: lscr.io/linuxserver/bookstack
        state: started
        restart_policy: unless-stopped
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"
        ports:
          - "8082:8082"
        volumes:
          - /NVMe/Docker/Bookstack:/config

  

