name: Pig Deploy

on:
  push:
    paths:
      - 'playbooks/Pig/**'
  pull_request:
    paths:
      - 'playbooks/Pig/**'
  schedule:
    - cron: '0 3 * * *'
  
jobs:
  ansible:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install sshpass
        run: |
          echo Fda2qRs!!! | sudo -S apt-get update
          echo Fda2qRs!!! | sudo -S apt-get install -y sshpass

      - name: Run Ansible playbook
        run: ansible-playbook -i inventory/hosts.yml playbooks/Pig/Docker.yml



